version: "3.7"

services:
# mysql service 
#  mysql:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: future_nations
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
#    volumes:
#      - ./data/mysql:/var/lib/mysql

# mongo service 
  # mongo:
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data/mongo:/data/db

# redis service
  # redis:
  #   image: redis:latest
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./data/redis:/data
      
# neo4j service
  neo4j:
    image: neo4j:5.2
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data/neo4j/conf:/conf
      - ./data/neo4j/data:/data
      - ./data/neo4j/import:/import
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/plugins:/plugins
    environment: 
      - NEO4J_AUTH=neo4j/password
      # - NEO4J_dbms_memory_pagecache_size=1G
      # - NEO4J_dbms.memory.heap.initial_size=1G
      # - NEO4J_dbms_memory_heap_max__size=1G

  frontend:
    image: amontology
    build: ./frontend/amontology
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/amontology/public:/app/public
      - ./frontend/amontology/src:/app/src
